version: '3.8'

services:
  web:
    build: .
    container_name: php-projintegrador
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - backend
  
  db:
    image: mysql:8.0
    container_name: mysql-projintegrador
    environment:
      MYSQL_ROOT_PASSWORD: "3727"           
      MYSQL_DATABASE: projintegrador         
      MYSQL_USER: root                  
      MYSQL_PASSWORD: "3727"              
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql:ro
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
