# Projeto Integrador - Erasmo Cardoso
# docker compose

version: '3.8'

services:
  web:
    build:
      context: .
      dockerfile: Dockerfile-php
    container_name: php-projintegrador
    ports:
      - "8080:80"
    volumes:
      - ./www:/var/www/html
    depends_on:
      - db
    networks:
      - backend

  db:
    build:
      context: .
      dockerfile: Dockerfile-mysql
    container_name: mysql-projintegrador
    environment:
      MYSQL_ROOT_PASSWORD: "3727"
      MYSQL_DATABASE: projintegrador
      MYSQL_USER: erasmo
      MYSQL_PASSWORD: "3727"
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
